GST-2: avfvideosrc split into two elements
fluendo/gst-plugins-bad pull request #7
Opened 2018-01-24 16:57 UTC by nachogarglez

OSX avfvideosrc is now split into two elements:
   
* avfvideosrc: source from cameras, etc
* osxscreencapsrc: source from displays
    
 osxscreencapsrc has also implemented a probe interface, 
and it is able to enumerate available displays.
A human-readable display can be selected
as source via 'device' property or
a ID via 'display-index'.
    
Note that display-index is not zero-based
but a 32 bit integer defined by Apple
    
This is first iteration of oscreencapsrc.
Device caps must be investigated more
deeply, altough their are working.

2018-01-25 08:41 UTC, nachogarglez commented on sys/applemedia/Makefile.am
> +    -Wl,-framework -Wl,IOKit
Note that we have to link with IOKit framework just to get the human readable Display name. It is linking with all the elements but only osxscreencapsrc needs it. Not ideal.

2018-01-29 17:11 UTC, marecki315 requested changes

2018-01-29 17:11 UTC, marecki315 commented on sys/applemedia/Makefile.am
> +    -Wl,-framework -Wl,IOKit
There was 'tab' indent before in this file, new lines that you are adding have spaces.

2018-01-30 10:19 UTC, marecki315 commented on sys/applemedia/Makefile.am
> +    -Wl,-framework -Wl,IOKit
The issue is also in other lines changed in this file

2018-01-30 10:29 UTC, marecki315 approved these changes

2018-01-30 10:54 UTC, merged