Updated DirectX9 API to DirectX9Ex
fluendo/gst-plugins-bad pull request #9
Opened 2018-05-17 08:47 UTC by nachogarglez

Legacy Win98/XP DirectX9 doesn't properly support multi monitor
fullscreen modes, because the D3D device adquires 'exclusive' use
of the hardware and doesn't allow other devices to be created at
some stages.
Upgrading API to  DirectX9Ex solves this issue.

"Ex" version was introduced in Windows Vista, so this patch also
deprecates Windows XP support.

2018-05-22 09:01 UTC, aslobodeniuk commented on sys/d3dvideosink/directx/directx9/dx9_d3d.h
>  typedef gpointer /* IDirect3D9* */ (WINAPI *LPDIRECT3DCREATE9) (UINT);
Looks like we're breaking support of dx9 , so why do we need this line?

2018-05-22 09:01 UTC, aslobodeniuk commented on sys/d3dvideosink/directx/directx9/dx9_d3d.h
>    LPDIRECT3DCREATE9 Direct3DCreate9;
... and this?

2018-05-28 16:54 UTC, turran requested changes

2018-05-28 16:54 UTC, turran commented on sys/d3dvideosink/d3dvideosink.c
> +
Do not include changes on the code style

2018-05-28 17:36 UTC, turran requested changes

2018-05-28 17:36 UTC, turran commented on sys/d3dvideosink/directx/directx9/dx9_d3d.h
> -
Also this one please

2018-05-29 08:13 UTC, turran approved these changes

2018-05-29 08:28 UTC, merged